### PR TITLE
Update Tensorflow how-to

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Review by lpaoletti — COMMENTED** [review]
In the intro, we have this phrase:
It can be used to solve many problems across different 
Please change to:
It can solve many problems across different

**Review by lpaoletti — COMMENTED** [review]
Current sentence:
The following section describes TensorFlow installation options.
The following sections contain options for installing TensorFlow.

Replace with:
The following section describes TensorFlow installation options.

**Review by peterjunpark — APPROVED** [review]

**Review by peterjunpark — CHANGES_REQUESTED** [review]

**Review by Naraenda — COMMENTED** [review]
Small comments since I just noticed this in my GitHub inbox. Otherwise NTA.

**Review by peterjunpark — APPROVED** [review]

**Review by Naraenda — COMMENTED** [review]
Sorry to nit again. Feel free to ignore if it's blocking anything important as other than that LGTM. Thanks!

**Pull request merged**
